services:
  - type: web
    name: khoj-nepal
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVER_PORT
        value: "8080"
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"
